# Generated by Django 5.0.1 on 2024-01-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_universitycampus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityCampus',
        ),
    ]
